In [13]:
import numpy as np
n=np.array([0,32,45,100,212])
x=np.array(n-32)*(5/9)
print("f:",n)
print("c:",x)

f: [  0  32  45 100 212]
c: [-17.77777778   0.           7.22222222  37.77777778 100.        ]


In [14]:
import  numpy as np
n=np.random.randint(1,99,size=1000)
a=np.mean(n)
b=np.var(n)
c=np.std(n)
print("Average",a)
print("Varience",b)
print("Standard deviation",c)

Average 50.035
Varience 822.497775
Standard deviation 28.679222008276305


In [35]:
import  numpy as np
n=np.array([30,45,90])
p=np.deg2rad([30,45,90])
print(p)
r=n*(np.pi/180)
print("radian:",r)

[0.52359878 0.78539816 1.57079633]
radian: [0.52359878 0.78539816 1.57079633]


In [45]:
import numpy as np
n=np.array([22,30,6,8,9])
d=np.diff(n)
print(d)
difference=n[1:]-n[:-1]
print("The difference is:",difference)

[  8 -24   2   1]
The difference is: [  8 -24   2   1]


In [53]:
import numpy as np
c=np.array([(1+2j),(5+4j),(2+3j),(7+7j),(6+6j),(1+3j),(5+1j)])
x=sorted(c)
p=np.sort(c)
print(x)
print(p)


[(1+2j), (1+3j), (2+3j), (5+1j), (5+4j), (6+6j), (7+7j)]
[1.+2.j 1.+3.j 2.+3.j 5.+1.j 5.+4.j 6.+6.j 7.+7.j]


In [54]:
import numpy as np
n=np.random.uniform(-10,10,10)
print(n)
r=n[n>4]
print(r)

[ 4.24928407 -0.4843438  -6.13911312  2.19712268  6.4103443  -3.58305433
 -6.22797609 -8.05608914 -2.99418141  7.65243189]
[4.24928407 6.4103443  7.65243189]


In [2]:
import numpy as np
n=np.arange(30,61,2)
print(n)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [8]:
import numpy as np
a=np.random.randint(1,10,6)
print(a)
n=int(input("Enter the element to search"))
index=np.where(a==n)[0]
if index.size>0:
    print("found at",index)
else:
    print("not found")

[7 1 1 3 7 6]
not found


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=np.sum(a)
t=np.sum(a,axis=1)
u=np.sum(a,axis=0)
print("total sum:",s)
print("sum of row:",t)
print("sum of column:",u)

total sum: 45
sum of row: [ 6 15 24]
sum of column: [12 15 18]


In [12]:
import numpy as np
a=np.array([1,2,3,4])
np.savetxt("array.txt",a)
l=np.loadtxt("array.txt")
print(l)

[1. 2. 3. 4.]
