In [34]:
import numpy as np

def matrix(name):
    n = int(input(f"Enter the number of rows of matrix {name}: "))
    p = int(input(f"Enter the number of columns of matrix {name}: "))

    matri = []

    for i in range(n):
        row = []
        for j in range(p):
            value = int(input(f"Enter element at [{i}][{j}] of matrix {name}: "))
            row.append(value)
        matri.append(row)

    matrix_np = np.array(matri)
    return matrix_np



A = matrix("A")
print("Matrix A:")
print(A)
B = matrix("B")
print("Matrix B:")
print(B)

x=np.dot(A,B)
print("The Dot product")
print(x)

y=np.transpose(A)
z=np.transpose(B)
print("The transpose of first matrix")
print(y)
print("The transpose of second matrix")
print(z)

l=np.trace(A)
m=np.trace(B)
print("The trace of first matrix",l)
print("The trace of second matrix",m)

n=np.linalg.matrix_rank(A)
o=np.linalg.matrix_rank(B)
print("The rank of first matrix",n)
print("The rank of second matrix",o)

h=np.linalg.det(A)
i=np.linalg.det(B)
print("The determinant of first matrix")
print(h)
print("The determinant of second matrix")
print(i)

r=np.linalg.inv(A)
s=np.linalg.inv(B)
print("The inverse of first matrix")
print(r)
print("The inverse of second matrix")
print(s)
print("The inverse of the matrix:/n",np.linalg.inv(A))

t=np.linalg.eig(A)
u=np.linalg.eig(B)
print("The eigenvector of first matrix")
print(t)
print("The eigenvector of second matrix")
print(u)





Matrix A:
[[1 2 3]
 [5 7 8]
 [9 4 1]]
Matrix B:
[[5 6 4]
 [7 8 9]
 [2 1 6]]
The Dot product
[[ 25  25  40]
 [ 90  94 131]
 [ 75  87  78]]
The transpose of first matrix
[[1 5 9]
 [2 7 4]
 [3 8 1]]
The transpose of second matrix
[[5 7 2]
 [6 8 1]
 [4 9 6]]
The trace of first matrix 9
The trace of second matrix 19
The rank of first matrix 3
The rank of second matrix 3
The determinant of first matrix
-19.999999999999996
The determinant of second matrix
14.999999999999966
The inverse of first matrix
[[ 1.25 -0.5   0.25]
 [-3.35  1.3  -0.35]
 [ 2.15 -0.7   0.15]]
The inverse of second matrix
[[ 2.6        -2.13333333  1.46666667]
 [-1.6         1.46666667 -1.13333333]
 [-0.6         0.46666667 -0.13333333]]
The inverse of the matrix:/n [[ 1.25 -0.5   0.25]
 [-3.35  1.3  -0.35]
 [ 2.15 -0.7   0.15]]
The eigenvector of first matrix
EigResult(eigenvalues=array([13.02729511,  0.35067361, -4.37796872]), eigenvectors=array([[ 0.2581046 ,  0.32897307, -0.29673449],
       [ 0.84226476, -0.81705318,